// Shared enums live here (leaf module) so monumentClassification.ts can import
// both the types AND the MAP_MONUMENTS value without creating a circular import.
export type MonumentCategoryId =
  | 'safe_zone'
  | 'tier_1'
  | 'tier_2'
  | 'tier_3'
  | 'offshore'
  | 'cave'
  | 'tunnel'
  | 'quarry'
  | 'roadside'
  | 'terrain'
  | 'rock_formation'
  | 'infrastructure'
  | 'event'
  | 'unknown';

export type MonumentConfidence = 'verified' | 'likely' | 'uncertain';

export interface MonumentCategory {
  id: MonumentCategoryId;
  name: string;
  description: string;
}

export interface MapMonument {
  id: string;
  name: string;
  categoryId: MonumentCategoryId;
  explanation: string;
  advantages: string[];
  disadvantages: string[];
  lootRelevance: string;
  radiationInfo: string;
  keycardsRequired: string[];
  quickTip: string;
  /** Honesty flag: how confident the curated content is. */
  confidence: MonumentConfidence;
  /** True when the mapping/content still needs owner verification. */
  needsOwnerReview?: boolean;
  imageUrl?: string;
}

export const MONUMENT_CATEGORIES: MonumentCategory[] = [
  { id: 'safe_zone', name: 'Safe Zones', description: 'No-combat zones for trading, repair and utilities.' },
  { id: 'tier_1', name: 'Tier 1 (Low)', description: 'Low radiation, basic loot. Ideal for fresh spawns.' },
  { id: 'tier_2', name: 'Tier 2 (Medium)', description: 'Medium radiation, better loot, mid-game hubs.' },
  { id: 'tier_3', name: 'Tier 3 (High)', description: 'High radiation, top-tier loot, endgame monuments.' },
  { id: 'offshore', name: 'Offshore', description: 'Oil Rigs and Underwater Labs.' },
  { id: 'quarry', name: 'Quarries', description: 'Static resource quarries (stone / sulfur / HQM).' },
  { id: 'roadside', name: 'Roadside', description: 'Small neutral roadside monuments.' },
  { id: 'cave', name: 'Caves', description: 'Natural caves — mostly base-building spots.' },
  { id: 'infrastructure', name: 'Infrastructure', description: 'Tunnels, substations and power lines — routing, not loot.' },
  { id: 'terrain', name: 'Terrain', description: 'Lakes, oases and ice — map features, not monuments.' },
  { id: 'rock_formation', name: 'Rock Formations', description: 'Buildable rocks — prime base spots, no loot.' },
];

export const MAP_MONUMENTS: MapMonument[] = [
  // ---------------------------------------------------------------- Safe Zones
  {
    id: 'outpost',
    name: 'Outpost',
    categoryId: 'safe_zone',
    explanation: 'A large, heavily guarded safe zone where players can trade resources, refine oil, and buy items.',
    advantages: ['Safe trading', 'Public recyclers', 'Vending machines for critical items'],
    disadvantages: ['High traffic area', 'Hostile if you carry weapons or deal damage nearby'],
    lootRelevance: 'No direct loot, but crucial for acquiring resources via trade (Stone/Wood, Scrap).',
    radiationInfo: 'None.',
    keycardsRequired: [],
    quickTip: 'Always unequip your weapons before entering the aggro radius to avoid being killed by turrets.',
    confidence: 'verified',
  },
  {
    id: 'bandit_camp',
    name: 'Bandit Camp',
    categoryId: 'safe_zone',
    explanation: 'A swamp-based safe zone featuring a casino, black market vendors, and public utilities.',
    advantages: ['Gambling (Scrap wheel)', 'Black market items (weapons)', 'Recyclers'],
    disadvantages: ['Laggy for some PCs', 'Easier to get roof-camped near the edges compared to Outpost'],
    lootRelevance: 'Trading and Scrap multiplication via gambling.',
    radiationInfo: 'None.',
    keycardsRequired: [],
    quickTip: 'You can buy a Mini-copter or Scrap Transport Helicopter here.',
    confidence: 'verified',
  },
  {
    id: 'fishing_village',
    name: 'Fishing Village',
    categoryId: 'safe_zone',
    explanation: 'A coastal safe zone. No combat. Buy boats, repair gear, and use vending machines.',
    advantages: ['Safe zone (no PvP)', 'Boat and item purchases', 'Repair bench + vending'],
    disadvantages: ['No direct loot', 'Fresh-spawn traffic on the coast'],
    lootRelevance: 'No direct loot — utility and boat/water access.',
    radiationInfo: 'None.',
    keycardsRequired: [],
    quickTip: 'You cannot be attacked inside the safe-zone radius.',
    confidence: 'verified',
  },
  {
    id: 'apartments_complex',
    name: 'Apartments Complex',
    categoryId: 'safe_zone',
    explanation: 'A safe-zone city block with rentable apartments, player shops, elevators, a train station and turrets. A social/commercial hub rather than a loot monument.',
    advantages: ['Trading and player shops', 'Safe zone', 'Train-station link'],
    disadvantages: ['No direct farm loot', 'Busy, turret-protected'],
    lootRelevance: 'No direct loot — commerce and social hub.',
    radiationInfo: 'None.',
    keycardsRequired: [],
    quickTip: 'Unequip weapons — it is a turret-protected safe zone.',
    confidence: 'verified',
  },

  // ------------------------------------------------------------- Tier 1 / small
  {
    id: 'gas_station',
    name: "Oxum's Gas Station",
    categoryId: 'tier_1',
    explanation: 'A small abandoned gas station. Great for early-game players looking for quick scrap.',
    advantages: ['Easy to loot', 'Green Keycard spawn', 'Public Recycler'],
    disadvantages: ['Very popular among fresh spawns', 'Low tier loot overall'],
    lootRelevance: 'Provides basic crates, food, and a Green Keycard.',
    radiationInfo: 'Minor to none.',
    keycardsRequired: [],
    quickTip: 'Check the office desk for the Green Keycard, and the roof for military crates.',
    confidence: 'verified',
  },
  {
    id: 'supermarket',
    name: 'Abandoned Supermarket',
    categoryId: 'tier_1',
    explanation: 'A decayed grocery store with basic loot and a recycler.',
    advantages: ['Green Keycard spawn', 'Recycler in the back', 'Food boxes'],
    disadvantages: ['High traffic for nakeds', 'Very exposed from the outside'],
    lootRelevance: 'Good source of food and basic scrap.',
    radiationInfo: 'None.',
    keycardsRequired: [],
    quickTip: 'Climb the shelves or the roof for hidden crates.',
    confidence: 'verified',
  },
  {
    id: 'lighthouse',
    name: 'Lighthouse',
    categoryId: 'tier_1',
    explanation: 'A coastal lighthouse with a climbable tower and a few crates. A notorious sniping position.',
    advantages: ['A few crates', 'High vantage point', 'Recycler on some layouts'],
    disadvantages: ['Very exposed', 'A well-known sniper magnet'],
    lootRelevance: 'Modest low-tier crates and barrels.',
    radiationInfo: 'Low.',
    keycardsRequired: [],
    quickTip: 'Great vantage — but you are also an easy target up top.',
    confidence: 'verified',
  },
  {
    id: 'warehouse',
    name: 'Warehouse',
    categoryId: 'tier_1',
    explanation: 'A small warehouse-style location. Its standalone status and exact loot should be verified against the live game.',
    advantages: ['Quick barrels/crates'],
    disadvantages: ['Low tier', 'Details not yet verified'],
    lootRelevance: 'Basic loot (unverified).',
    radiationInfo: 'Likely none (unverified).',
    keycardsRequired: [],
    quickTip: 'Treat as a quick early stop until confirmed.',
    confidence: 'likely',
    needsOwnerReview: true,
  },
  {
    id: 'jungle_ruins',
    name: 'Jungle Ruins',
    categoryId: 'tier_1',
    explanation: 'A small ruined monument from the Jungle update with light vertical parkour and a few loot boxes.',
    advantages: ['Low competition', 'Chance at a military crate'],
    disadvantages: ['Small', 'Jungle exposure'],
    lootRelevance: 'A handful of crates.',
    radiationInfo: 'None to low.',
    keycardsRequired: [],
    quickTip: 'A quick detour when passing through the jungle biome.',
    confidence: 'verified',
  },

  // -------------------------------------------------------------- Tier 2 / mid
  {
    id: 'dome',
    name: 'The Dome',
    categoryId: 'tier_2',
    explanation: 'A massive spherical industrial ruin. Requires parkour to reach the top.',
    advantages: ['4 Military Crates at the top', 'No keycards needed', 'Crude oil barrels'],
    disadvantages: ['Parkour can be deadly if you fall', 'Snipers can target you while you climb'],
    lootRelevance: 'Excellent mid-game loot for no keycard investment.',
    radiationInfo: 'Low (basic protection recommended).',
    keycardsRequired: [],
    quickTip: 'Practice the jumps on a creative server. Bring meds for fall damage.',
    confidence: 'verified',
  },
  {
    id: 'water_treatment',
    name: 'Water Treatment Plant',
    categoryId: 'tier_2',
    explanation: 'A sprawling facility with a card puzzle and many jump puzzles.',
    advantages: ['Huge amount of scattered loot', 'Card puzzle progression', 'Multiple recyclers'],
    disadvantages: ['Very large area, hard to defend', 'Lots of hiding spots'],
    lootRelevance: 'High volume of crates, great for scrap runs.',
    radiationInfo: 'Medium. Protection recommended inside the main building.',
    keycardsRequired: ['green', 'blue'],
    quickTip: 'You can reach a lot of crates via jump puzzles without keycards.',
    confidence: 'verified',
  },
  {
    id: 'airfield',
    name: 'Airfield',
    categoryId: 'tier_2',
    explanation: 'A large open monument with hangars, a control tower and scientists.',
    advantages: ['Recyclers on site', 'Good crate density', 'Card puzzle'],
    disadvantages: ['Very open — high PvP', 'Scientist resistance'],
    lootRelevance: 'Strong mid-tier crates and components.',
    radiationInfo: 'Medium.',
    keycardsRequired: [],
    quickTip: 'Extremely exposed — expect snipers on the open tarmac.',
    confidence: 'verified',
  },
  {
    id: 'harbor_large',
    name: 'Large Harbor',
    categoryId: 'tier_2',
    explanation: 'The larger of the two coastal harbors, with cranes, containers and a scientist presence. A Cargo Ship docking point.',
    advantages: ['Recycler on site', 'Scrap and component crates', 'Cargo Ship docks here'],
    disadvantages: ['Open, exposed layout', 'Coastal PvP traffic'],
    lootRelevance: 'Mid-tier crates and components; recycler for scrap.',
    radiationInfo: 'Low to none in most areas.',
    keycardsRequired: [],
    quickTip: 'Watch the water — players arrive by boat.',
    confidence: 'verified',
  },
  {
    id: 'harbor_small',
    name: 'Small Harbor',
    categoryId: 'tier_2',
    explanation: 'The smaller coastal harbor variant with a crane, boats and a modest loot spread.',
    advantages: ['Recycler on site', 'Boat access', 'Quieter than the large harbor'],
    disadvantages: ['Exposed', 'Coastal traffic'],
    lootRelevance: 'Lower-mid crates and components.',
    radiationInfo: 'Low to none.',
    keycardsRequired: [],
    quickTip: 'A calmer scrap stop than the large harbor.',
    confidence: 'verified',
  },
  {
    id: 'ferry_terminal',
    name: 'Ferry Terminal',
    categoryId: 'tier_2',
    explanation: 'A coastal terminal tied to the ferry/cargo system, with crates and scientists.',
    advantages: ['Recycler on site', 'Mid-tier crates', 'Usually quiet'],
    disadvantages: ['Exposed coastal position'],
    lootRelevance: 'Mid-tier crates and components.',
    radiationInfo: 'Low.',
    keycardsRequired: [],
    quickTip: 'A calm farming spot away from the mainland rush.',
    confidence: 'verified',
  },
  {
    id: 'junkyard',
    name: 'Junkyard',
    categoryId: 'tier_2',
    explanation: 'A scrap yard with a magnet crane, car crusher and barrels. No keycard needed.',
    advantages: ['Recycler and diesel', 'No card required', 'Car crusher for components'],
    disadvantages: ['Little cover', 'Draws farmers'],
    lootRelevance: 'Barrels and components — a solid quiet scrap run.',
    radiationInfo: 'None.',
    keycardsRequired: [],
    quickTip: 'Underrated, low-radiation scrap location.',
    confidence: 'verified',
  },
  {
    id: 'satellite_dish',
    name: 'Satellite Dish',
    categoryId: 'tier_2',
    explanation: 'A small monument centered on a large dish, with a fuse/card puzzle and scientists.',
    advantages: ['Recycler', 'Simple card puzzle'],
    disadvantages: ['Limited loot', 'Little cover'],
    lootRelevance: 'Modest mid-tier crates.',
    radiationInfo: 'Low.',
    keycardsRequired: ['blue'],
    quickTip: 'A quick, usually low-traffic run.',
    confidence: 'verified',
  },
  {
    id: 'sewer_branch',
    name: 'Sewer Branch',
    categoryId: 'tier_2',
    explanation: 'A compact monument with a green/blue puzzle, scientists and lockable doors.',
    advantages: ['Recycler', 'Lower competition', 'Lockable rooms for safe looting'],
    disadvantages: ['Tight interior', 'Scientists'],
    lootRelevance: 'Brown and military crates.',
    radiationInfo: 'Low to medium.',
    keycardsRequired: ['green', 'blue'],
    quickTip: 'Great solo spot — doors can be locked behind you.',
    confidence: 'verified',
  },
  {
    id: 'radtown',
    name: 'Radtown',
    categoryId: 'tier_2',
    explanation: 'The reworked Radtown (World 2 update). No scientists and no card puzzle, but a recycler, radioactive water and default/military/elite crates.',
    advantages: ['Recycler on site', 'Chance at elite crates', 'No card puzzle'],
    disadvantages: ['Radiation present', 'Open and popular'],
    lootRelevance: 'Default through elite crates — a low-barrier crate run.',
    radiationInfo: 'Present — bring protection.',
    keycardsRequired: [],
    quickTip: 'Low-barrier crate run; mind the radioactive water.',
    confidence: 'verified',
  },
  {
    id: 'jungle_ziggurat',
    name: 'Jungle Ziggurat',
    categoryId: 'tier_2',
    explanation: 'An overgrown pyramid monument in the jungle biome, added in the Jungle update.',
    advantages: ['Distinct vertical layout', 'Crates to loot'],
    disadvantages: ['Jungle traffic', 'Layout still settling in the meta'],
    lootRelevance: 'Mid-tier crates (varies by version).',
    radiationInfo: 'Low.',
    keycardsRequired: [],
    quickTip: 'A newer monument — expect players still learning it.',
    confidence: 'verified',
  },

  // ------------------------------------------------------------- Tier 3 / large
  {
    id: 'launch_site',
    name: 'Launch Site',
    categoryId: 'tier_3',
    explanation: 'The ultimate mainland monument. Features the Bradley APC and a large Red card puzzle.',
    advantages: ['Elite crates', 'Bradley APC drops high-tier loot', 'Huge scrap potential'],
    disadvantages: ['Extremely high radiation', 'Guarded by Bradley APC', 'Clan PvP hotspot'],
    lootRelevance: 'Endgame loot, C4, rockets, and high-tier weapons.',
    radiationInfo: 'Extreme. Full protection and meds required for the main building.',
    keycardsRequired: ['green', 'red'],
    quickTip: 'Wait for the Bradley to be on the far side before crossing open areas.',
    confidence: 'verified',
  },
  {
    id: 'military_tunnels',
    name: 'Military Tunnels',
    categoryId: 'tier_3',
    explanation: 'An underground complex with aggressive scientists and a red-card puzzle.',
    advantages: ['Elite military crates', 'Recycler'],
    disadvantages: ['Aggressive scientists (grenades)', 'High radiation'],
    lootRelevance: 'Elite-tier military loot.',
    radiationInfo: 'High — full protection.',
    keycardsRequired: ['red'],
    quickTip: 'The scientists are deadly — bring strong gear and meds.',
    confidence: 'verified',
  },
  {
    id: 'power_plant',
    name: 'Power Plant',
    categoryId: 'tier_3',
    explanation: 'A high-radiation industrial monument with a red-card puzzle, scientists and a vertical layout.',
    advantages: ['Red-card room', 'Recycler', 'High-tier crates'],
    disadvantages: ['High radiation', 'Vertical death traps in PvP'],
    lootRelevance: 'High-tier military plus a locked-crate chance.',
    radiationInfo: 'High — full protection.',
    keycardsRequired: ['red'],
    quickTip: 'Bring radiation protection and plenty of meds.',
    confidence: 'verified',
  },
  {
    id: 'train_yard',
    name: 'Train Yard',
    categoryId: 'tier_3',
    explanation: 'An industrial rail yard with a card puzzle, a refinery and scientists.',
    advantages: ['Refinery and recycler', 'Component crates', 'Diesel on site'],
    disadvantages: ['Often contested', 'Radiation'],
    lootRelevance: 'Mid-to-high tier crates and components.',
    radiationInfo: 'Medium to high.',
    keycardsRequired: ['blue', 'red'],
    quickTip: 'Refinery and diesel make it a strong scrap-and-fuel stop.',
    confidence: 'verified',
  },
  {
    id: 'excavator',
    name: 'Giant Excavator Pit',
    categoryId: 'tier_3',
    explanation: 'An operable mining event, diesel-powered, with military crates and diesel barrels.',
    advantages: ['Resource excavator event', 'Military crates', 'Recycler'],
    disadvantages: ['Loud and attention-drawing when running', 'Open pit'],
    lootRelevance: 'Military crates plus resource output when active.',
    radiationInfo: 'Low.',
    keycardsRequired: [],
    quickTip: 'Running the excavator needs diesel and draws other players.',
    confidence: 'verified',
  },
  {
    id: 'missile_silo',
    name: 'Nuclear Missile Silo',
    categoryId: 'tier_3',
    explanation: 'A large underground complex with scientists and a card/fuse puzzle.',
    advantages: ['High-tier crates', 'Recycler'],
    disadvantages: ['Maze-like interior', 'Radiation'],
    lootRelevance: 'High-tier loot (exact spread varies by version).',
    radiationInfo: 'Medium to high underground.',
    keycardsRequired: [],
    quickTip: 'It is a long fight-out — bring meds and manage your exit.',
    confidence: 'verified',
  },
  {
    id: 'arctic_base',
    name: 'Arctic Research Base',
    categoryId: 'tier_3',
    explanation: 'A snow-biome research base with a fuse puzzle, scientists and a snowmobile spawn.',
    advantages: ['Component and military crates', 'Snowmobile spawn', 'Recycler'],
    disadvantages: ['Cold, exposed snow biome', 'Scientist resistance'],
    lootRelevance: 'Mid-to-high tier crates.',
    radiationInfo: 'Low to medium.',
    keycardsRequired: [],
    quickTip: 'Dress warm and bring meds for the fight.',
    confidence: 'verified',
  },
  {
    id: 'military_base',
    name: 'Military Base',
    categoryId: 'tier_3',
    explanation: 'A fenced military compound (the Abandoned / Desert Military Base) with scientists and a puzzle. Exact naming and layout should be verified against the live game.',
    advantages: ['Military and elite crates', 'Recycler'],
    disadvantages: ['Radiation', 'Scientist resistance'],
    lootRelevance: 'High-tier military loot (varies by version).',
    radiationInfo: 'Medium — protection recommended.',
    keycardsRequired: [],
    quickTip: 'Bring radiation protection and solid gear.',
    confidence: 'likely',
    needsOwnerReview: true,
  },

  // ----------------------------------------------------------------- Offshore
  {
    id: 'large_oil_rig',
    name: 'Large Oil Rig',
    categoryId: 'offshore',
    explanation: 'A massive offshore drilling platform guarded by scientists. Features a timed locked-crate event.',
    advantages: ['Locked crate guarantees high-tier loot', 'Heavy scientists drop good weapons', 'Isolated from fresh spawns'],
    disadvantages: ['Only reachable by boat or heli', 'Counters can trap you on the rig'],
    lootRelevance: 'Endgame. One of the best places for Tier 3 weapons and armor.',
    radiationInfo: 'None by default; radiation hits the rig if players linger after the crate unlocks.',
    keycardsRequired: [],
    quickTip: 'Access is card-free (by boat); hold the crane or helipad against counters.',
    confidence: 'verified',
  },
  {
    id: 'small_oil_rig',
    name: 'Small Oil Rig',
    categoryId: 'offshore',
    explanation: 'A smaller offshore rig guarded by scientists, with a timed locked-crate event. Soloable with care.',
    advantages: ['Elite/locked crate', 'Recycler', 'Soloable'],
    disadvantages: ['Boat or heli access only', 'Vulnerable to counter-attacks'],
    lootRelevance: 'High-tier loot from the locked crate and scientists.',
    radiationInfo: 'None until the crate radiation event.',
    keycardsRequired: [],
    quickTip: 'Access is card-free by boat; watch for counters while the crate unlocks.',
    confidence: 'verified',
  },
  {
    id: 'underwater_labs',
    name: 'Underwater Labs',
    categoryId: 'offshore',
    explanation: 'A procedurally generated underwater complex reached by submarine, with scientists and card-locked rooms.',
    advantages: ['Recycler', 'Varied crates', 'Isolated from land PvP'],
    disadvantages: ['Submarine required', 'Disorienting procedural layout'],
    lootRelevance: 'Mid-to-high tier, procedurally placed.',
    radiationInfo: 'None.',
    keycardsRequired: [],
    quickTip: 'Bring a sub and manage your oxygen between sections.',
    confidence: 'verified',
  },

  // ------------------------------------------------------------------ Quarries
  {
    id: 'sulfur_quarry',
    name: 'Sulfur Quarry',
    categoryId: 'quarry',
    explanation: 'A static, diesel-powered quarry that outputs sulfur ore. No crate loot.',
    advantages: ['Sulfur ore source', 'Map landmark'],
    disadvantages: ['No crate loot', 'Draws farmers'],
    lootRelevance: 'Resource (sulfur), not crates.',
    radiationInfo: 'None.',
    keycardsRequired: [],
    quickTip: 'A resource run, not a loot run — needs diesel to operate.',
    confidence: 'verified',
  },
  {
    id: 'stone_quarry',
    name: 'Stone Quarry',
    categoryId: 'quarry',
    explanation: 'A static, diesel-powered quarry that outputs stone. No crate loot.',
    advantages: ['Stone ore source', 'Map landmark'],
    disadvantages: ['No crate loot'],
    lootRelevance: 'Resource (stone), not crates.',
    radiationInfo: 'None.',
    keycardsRequired: [],
    quickTip: 'Resource output only — bring diesel to run it.',
    confidence: 'verified',
  },
  {
    id: 'hqm_quarry',
    name: 'HQM Quarry',
    categoryId: 'quarry',
    explanation: 'A static, diesel-powered quarry that outputs High Quality Metal ore. No crate loot.',
    advantages: ['HQM ore source', 'Map landmark'],
    disadvantages: ['No crate loot', 'Attracts farmers'],
    lootRelevance: 'Resource (HQM), not crates.',
    radiationInfo: 'None.',
    keycardsRequired: [],
    quickTip: 'Valuable HQM output, but purely a resource stop.',
    confidence: 'verified',
  },

  // ------------------------------------------------------------------ Roadside
  {
    id: 'ranch',
    name: 'Ranch',
    categoryId: 'roadside',
    explanation: 'A neutral roadside ranch with hitching posts and a few loot boxes. No scientists.',
    advantages: ['Quick roadside loot', 'Build landmark'],
    disadvantages: ['Low loot', 'Fresh-spawn spawn area'],
    lootRelevance: 'Basic boxes and barrels.',
    radiationInfo: 'None.',
    keycardsRequired: [],
    quickTip: 'A handy early landmark with modest reward.',
    confidence: 'verified',
  },
  {
    id: 'large_barn',
    name: 'Large Barn',
    categoryId: 'roadside',
    explanation: 'A neutral roadside barn with storage boxes. No scientists.',
    advantages: ['Roadside boxes', 'Build landmark'],
    disadvantages: ['Low loot'],
    lootRelevance: 'Basic boxes and barrels.',
    radiationInfo: 'None.',
    keycardsRequired: [],
    quickTip: 'A quick stop while travelling the roads.',
    confidence: 'verified',
  },
  {
    id: 'water_well',
    name: 'Water Well',
    categoryId: 'roadside',
    explanation: 'A small roadside well. Minimal loot; primarily a water source and landmark.',
    advantages: ['Water source', 'Landmark'],
    disadvantages: ['Very low loot'],
    lootRelevance: 'Minimal.',
    radiationInfo: 'None.',
    keycardsRequired: [],
    quickTip: 'Not worth a detour for loot alone.',
    confidence: 'verified',
  },

  // --------------------------------------------------------------------- Caves
  {
    id: 'cave',
    name: 'Caves',
    categoryId: 'cave',
    explanation: 'Natural cave systems that come in several size/difficulty variants. Mostly valued as building spots rather than loot.',
    advantages: ['Hidden base locations', 'Multiple exits in larger caves'],
    disadvantages: ['Dark and tight', 'Easy to get trapped inside'],
    lootRelevance: 'Light — barrels and boxes only.',
    radiationInfo: 'Usually none (low in some).',
    keycardsRequired: [],
    quickTip: 'Prized for base-building far more than for loot.',
    confidence: 'verified',
  },

  // ------------------------------------------------------------ Rock formations
  {
    id: 'rock_formation',
    name: 'Rock Formations',
    categoryId: 'rock_formation',
    explanation: 'Buildable rock formations (revamped in World 2.0) such as God Rocks, Anvil Rock and 3-Wall Rock. Not loot — prime base-building spots.',
    advantages: ['Strong base foundations', 'Natural cover'],
    disadvantages: ['No loot', 'Contested build spots'],
    lootRelevance: 'None — a building feature.',
    radiationInfo: 'None.',
    keycardsRequired: [],
    quickTip: 'Key for compact, defensible bases.',
    confidence: 'verified',
  },

  // ----------------------------------------------------------- Infrastructure
  {
    id: 'tunnel_entrance',
    name: 'Tunnel Entrance',
    categoryId: 'infrastructure',
    explanation: 'An entrance to the underground train-tunnel network. An access/route feature rather than a loot monument.',
    advantages: ['Underground access', 'Route and escape option'],
    disadvantages: ['Not a loot spot'],
    lootRelevance: 'None directly at the entrance.',
    radiationInfo: 'Low.',
    keycardsRequired: [],
    quickTip: 'A gateway into the tunnel system.',
    confidence: 'verified',
  },
  {
    id: 'power_substation',
    name: 'Power Substation',
    categoryId: 'infrastructure',
    explanation: 'An electrical substation (small or big). Roadside power infrastructure with minor components; relevant for routing and electricity context.',
    advantages: ['Minor components', 'Route landmark'],
    disadvantages: ['Very low loot'],
    lootRelevance: 'Minor.',
    radiationInfo: 'None.',
    keycardsRequired: [],
    quickTip: 'More a map landmark than a loot stop.',
    confidence: 'verified',
  },
  {
    id: 'powerline',
    name: 'Powerline',
    categoryId: 'infrastructure',
    explanation: 'Powerline corridors crossing the map. A routing/terrain feature, not a monument.',
    advantages: ['Open travel route', 'Orientation landmark'],
    disadvantages: ['Exposed'],
    lootRelevance: 'None.',
    radiationInfo: 'None.',
    keycardsRequired: [],
    quickTip: 'Useful for orientation and following roads.',
    confidence: 'verified',
  },

  // ------------------------------------------------------------------- Terrain
  {
    id: 'lake',
    name: 'Lake',
    categoryId: 'terrain',
    explanation: 'An inland lake. A terrain feature — no loot. Relevant for water access, farming and base placement.',
    advantages: ['Water access', 'Build/farm context'],
    disadvantages: ['Terrain only'],
    lootRelevance: 'None.',
    radiationInfo: 'None.',
    keycardsRequired: [],
    quickTip: 'Consider it for water and building proximity.',
    confidence: 'verified',
  },
  {
    id: 'oasis',
    name: 'Oasis',
    categoryId: 'terrain',
    explanation: 'A desert oasis with water and greenery. A terrain feature with base/farm relevance, no loot.',
    advantages: ['Water in the desert', 'Build/farm context'],
    disadvantages: ['Terrain only'],
    lootRelevance: 'None.',
    radiationInfo: 'None.',
    keycardsRequired: [],
    quickTip: 'A rare water and vegetation point in the desert.',
    confidence: 'verified',
  },
  {
    id: 'ice_lake',
    name: 'Ice Lake',
    categoryId: 'terrain',
    explanation: 'A frozen lake in the snow biome. A terrain feature; any surface crates vary by version.',
    advantages: ['Snow-biome landmark'],
    disadvantages: ['Exposed and cold'],
    lootRelevance: 'None reliably.',
    radiationInfo: 'None.',
    keycardsRequired: [],
    quickTip: 'A terrain feature, not a loot run.',
    confidence: 'verified',
  },
  {
    id: 'iceberg',
    name: 'Iceberg',
    categoryId: 'terrain',
    explanation: 'An ocean iceberg in cold waters. A terrain feature.',
    advantages: ['Ocean landmark'],
    disadvantages: ['Remote'],
    lootRelevance: 'None.',
    radiationInfo: 'None.',
    keycardsRequired: [],
    quickTip: 'A navigation landmark on the water.',
    confidence: 'verified',
  },
];
